let programs=[];let commonDictionary=[];let programDictionary=[];
const qs=(s,r=document)=>r.querySelector(s);const qsa=(s,r=document)=>[...r.querySelectorAll(s)];
init();
async function init(){try{const [p,c,d]=await Promise.all([fetch('data/programs.json'),fetch('data/common_dictionary.csv'),fetch('data/program_dictionary.csv')]);programs=await p.json();commonDictionary=parseCommonCsv(await c.text());programDictionary=parseProgramCsv(await d.text());bind();renderDirectory();}catch(e){qs('#results').innerHTML=`<section class="card interest-map">データを読み込めませんでした。ローカルサーバーから開いてください。<br>${escapeHtml(e.message)}</section>`}}
function bind(){qs('#compass-form').onsubmit=e=>{e.preventDefault();runSearch(qs('#query').value||'')};qsa('[data-example]').forEach(b=>b.onclick=()=>{qs('#query').value=b.dataset.example;qs('#query').focus()})}
function parseCsv(text=''){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i],nx=text[i+1];if(ch==='"'&&q&&nx==='"'){cell+='"';i++}else if(ch==='"'){q=!q}else if(ch===','&&!q){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&nx==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows}
function parseCommonCsv(text){const rows=parseCsv(text);const h=rows.shift();const idx=Object.fromEntries(h.map((x,i)=>[x,i]));return rows.map(r=>({word:r[idx.word]||'',synonym:r[idx.synonym]||'',tag:r[idx.tag]||'',weight:Number(r[idx.weight]||1)})).filter(x=>x.word&&x.tag)}
function parseProgramCsv(text){const rows=parseCsv(text);const h=rows.shift();const idx=Object.fromEntries(h.map((x,i)=>[x,i]));return rows.map(r=>({program_id:r[idx.program_id]||'',word:r[idx.word]||'',synonym:r[idx.synonym]||'',field:r[idx.field]||'',weight:Number(r[idx.weight]||1),source:r[idx.source]||'',needs_review:r[idx.needs_review]==='True'||r[idx.needs_review]==='true'})).filter(x=>x.program_id&&x.word)}
function normalize(v=''){return String(v).normalize('NFKC').toLowerCase().replace(/癌|ガン/g,'がん').replace(/[、。,.!?！？「」『』（）()［］\[\]【】・/／\\\s]/g,'')}
function inputTerms(text=''){const whole=normalize(text);const rough=String(text).normalize('NFKC').replace(/[、。,.!?！？「」『』（）()［］\[\]【】・/／\\]/g,' ').split(/\s+/).flatMap(c=>c.split(/(?:が(?!ん)|を|に|へ|で|と|の|は|も|や|って|です|ます|した|したい|たい|好き|興味|気になる|面白い|面白そう|知りたい|ありますか|について|から|まで|なら|けど|でも)/g)).map(normalize).filter(t=>t.length>=2);return new Set([whole,...rough])}
function analyze(text){const n=normalize(text);const tags=new Map();const matched=[];commonDictionary.forEach(e=>{const cands=[e.word,...e.synonym.split('|')].map(x=>x.trim()).filter(Boolean);if(!cands.some(c=>n.includes(normalize(c))))return;matched.push(e);tags.set(e.tag,(tags.get(e.tag)||0)+e.weight)});return{tags:[...tags.entries()].sort((a,b)=>b[1]-a[1]).map(([tag,score])=>({tag,score})),tagScores:tags,matched}}
function scorePrograms(text,analysis){const n=normalize(text);const terms=inputTerms(text);const tagScores=analysis.tagScores;const normTags=new Map([...tagScores.entries()].map(([t,w])=>[normalize(t),w]));const byId=programDictionary.reduce((m,e)=>{(m[e.program_id]||(m[e.program_id]=[])).push(e);return m},{});return programs.map(p=>{let score=0;const matched=new Map();(byId[p.id]||[]).forEach(e=>{const cands=[e.word,...e.synonym.split('|')].map(x=>x.trim()).filter(Boolean);const exact=cands.some(c=>terms.has(normalize(c)));const direct=exact||cands.some(c=>n.includes(normalize(c)));if(direct){const w=e.weight*(exact?3:2);score+=w;matched.set(e.word,(matched.get(e.word)||0)+w);return}const tag=cands.find(c=>tagScores.has(c)||normTags.has(normalize(c)));if(tag){const tw=tagScores.get(tag)||normTags.get(normalize(tag))||e.weight;const w=Math.max(1,Math.max(e.weight,tw)*.75);score+=w;matched.set(e.word,(matched.get(e.word)||0)+w)}});p.tags.forEach(t=>{if(tagScores.has(t)){const w=Math.max(.25,tagScores.get(t)*.2);score+=w;matched.set(t,(matched.get(t)||0)+w)}});const reason=[...matched.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'ja')).map(([x])=>x);return{program:p,score,reason}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.program.department.localeCompare(b.program.department,'ja')).slice(0,8)}
function runSearch(raw){const input=raw.trim();if(!input){qs('#results').innerHTML='<section class="card interest-map">一言でいいので、気になることを書いてみてください。</section>';return}const analysis=analyze(input);const matches=scorePrograms(input,analysis);renderResults(input,analysis,matches)}
function renderResults(input,analysis,matches){const tags=analysis.tags.slice(0,10);qs('#results').innerHTML=`<section class="card interest-map"><span class="eyebrow">INTEREST MAP</span><h2>あなたの興味を整理しました</h2>${tags.length?`<div class="tag-list">${tags.map(t=>`<span>✓ ${escapeHtml(t.tag)}</span>`).join('')}</div>`:'<p>この言葉はまだ辞書で学習中です。結果は参考程度に見てください。</p>'}</section><section><div class="section-head"><span class="eyebrow">MATCH</span><h2>おすすめの学科</h2></div><div class="match-grid"></div></section>`;const grid=qs('.match-grid');if(!matches.length){grid.innerHTML='<section class="card interest-map">一致する学科がまだ少ないようです。辞書の育成候補です。</section>';return}matches.slice(0,6).forEach(m=>grid.appendChild(programCard(m)))}
function programCard(item){const p=item.program;const el=document.createElement('article');el.className='program-card card';el.innerHTML=`<span class="score">${Math.round(item.score)}</span><span class="faculty">${escapeHtml(p.faculty)}</span><strong>${escapeHtml(p.department)}</strong><p>${escapeHtml(p.summary)}</p><div class="reasons">${item.reason.slice(0,5).map(r=>`<em>${escapeHtml(r)}</em>`).join('')}</div><a class="open-link" href="${escapeHtml(p.official_url)}" target="_blank" rel="noreferrer">公式ページへ</a>`;return el}
function renderDirectory(){const list=qs('#program-list');list.innerHTML='';programs.forEach(p=>{const el=document.createElement('article');el.className='mini';el.innerHTML=`<span>${escapeHtml(p.faculty)}</span><strong>${escapeHtml(p.department)}</strong>`;list.appendChild(el)})}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
